import { createMDX } from "fumadocs-mdx/next";

// A static export (`out/`), served from the domain root (fragiola.com). Every page is a
// directory with an index.html, so a static host resolves /ui/docs/atoms/clickable/ without
// rewrite rules.
//
// What lives under public/ is generated by scripts/prepare-site.ts from .sources/: each
// project's embed apps (public/<slug>/embed/<fw>/, built by the project for that exact base), the
// code panel's files (public/<slug>/code/) and the merged shadcn registry (public/r/). In dev,
// scripts/dev.ts puts a proxy in front of `next dev` that sends /<slug>/embed/** to a project's
// `site:dev` instead.

/** @type {import('next').NextConfig} */
const nextConfig = {
    pageExtensions: ["ts", "tsx"],
    output: "export",
    trailingSlash: true,
    images: { unoptimized: true },
    // AGENTS.md is this repo's own: `next dev` must not write one
    agentRules: false,
};

const withMDX = createMDX();

export default withMDX(nextConfig);
