import { createMDX } from "fumadocs-mdx/next";

// A static export (`out/`), served from the domain root (fragiola.com).
// Every page is a directory with an index.html, so a static host resolves
// /ui/docs/atoms/clickable/ without rewrite rules.
//
// What lives in public/ is generated by scripts/prepare-site.ts from
// .sources/: each project's examples app (public/<slug>/examples/<fw>/,
// built by the project for that exact base) and the merged shadcn registry
// (public/r/).

/** @type {import('next').NextConfig} */
const nextConfig = {
    pageExtensions: ["ts", "tsx"],
    output: "export",
    trailingSlash: true,
    images: { unoptimized: true },
};

const withMDX = createMDX();

export default withMDX(nextConfig);
